version: "3.7"

services:
  nginx:
    image: nginx:1.17.2-alpine
    ports: 
      - "8080:8080"
    networks:
      - backend
    volumes:
      - "./nginx-default.conf:/etc/nginx/conf.d/default.conf"
      
  app:
    build: .
    networks:
      - backend

networks:
  backend: