version: "3.7"

services:
  lb:
    image: haproxy:2.1
    ports: 
      - "8080:8080"
      - "8084:8084"
    networks:
      - backend
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    depends_on:
      - app
      
  app:
    build: .
    networks:
      - backend

networks:
  backend:
